### ISSUE TITLE
We don't need this level of details in the definined schemas

### ISSUE THREAD

**Issue by syphax-bouazzouni** [FAIR-IMPACT/MOD-API#31]
Currently we see too much schemas in the responses list, it a bit hard to read, can we simplify it to have only the following: `SemanticArtefact`, `SemanticArtefactCatalog`, `SemanticArtefactDistribution`. 

All the others are not yet defined by MOD I think, and can left open for the  implementers to decide what to return as Object.

![Image](https://github.com/user-attachments/assets/a4983fb9-01a9-49ea-8d75-c2774d7a568c)

**Comment by syphax-bouazzouni** [comment]
@imadbourouche you told me about a PR doing this ?

**Comment by imadbourouche** [comment]
> [@imadbourouche](https://github.com/imadbourouche) you told me about a PR doing this ?

Yes but i didn't do it yet

**Comment by antony-wilson** [comment]
I do not know if there is a way to hide items in the schema. The only way I have found is to include these objects directly rather than make references to them. This leads to a lot of duplication of code. There are 13 references to `rdfs:Literal`, for example in `modSemanticArtefactCatalog` we have:

```
            dcterms:alternative:
              title: alternative title
              description: An alternative name for the resource.
              $ref: "#/components/schemas/rdfsLiteral"
```

Where we define `#/components/schemas/rdfsLiteral` as:

```
    rdfsLiteral:
      type: object
      properties:
        '@type':
          title: Literal
          description: The class of literal values, eg. textual strings and integers.
          example: rdfs:Literal
        '@value':
          example: Lorem ipsum
```

Each of these 13 references to `rdfs:Literal` would have to be replaced with the definition of the object
